import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body>
        <nav>
          <h1>My navbar</h1>
        </nav>
        {children}
      </body>
    </html>
  );
}
